apiVersion: v1
kind: Secret
metadata:
   name: mongodb-secret # this name u hv to give while using this values
type: Opaque #default value here
data:
   mongo-root-username: 4oCYdXNlcm5hbWXigJk=   #run echo -n  ‘username’ | base64
   mongo-root-password: 4oCYcGFzc3dvcmTigJk=   #run echo -n 'password'


#1.run this file in cmd then fikle will in inetgarted
#2.kubectl get secret