apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  lables: 
    app: mongo-express
spec: #specification for deployment 
  selector:
    matchLabels:
      app: mongo-express
  replicas: 1 # tells deployment to run 2 pods matching the template(no of pods we want)
  template:
    metadata:
      labels:
        app: mongo-express
    spec: #specifications for pods
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
        env: 
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom: 
             secretKeyRef:
               name: mongodb-secret
               key: mongo-root-username
        - name : ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom: 
             secretKeyRef:
               name: mongodb-secret
               key: mongo-root-username
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom: 
             configMapKeyRef:
               name: mongodb-configmap  # name from config
               key: mongo-root-username

---
#for external service 
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec: #specification for deployment 
  selector:
      app: mongo-express
  type: LoadBalancer
  ports: 
     - protocol: TCP
       port: 8081
       targetPort: 8081
       nodePort: 30000      #this is external port where service will open