apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec: #specification for deployment 
  selector:
    matchLabels:
      app: nginx
  replicas: 4 # tells deployment to run 2 pods matching the template(no of pods we want)
  template:
    metadata:
      labels:
        app: nginx
    spec: #specifications for pods
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80